Conda name: watertap3
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0.1
  - dask-core=2.20.0
  - decorator=4.4.2
  - flask=1.1.2
  - hdf5=1.10.4
  - html5lib=1.1
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - json5=0.9.5
  - jsonschema=3.2.0
  - lazy-object-proxy=1.4.3
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - networkx=2.4
  - numba=0.50.1
  - numpy-base=1.18.5
  - pep8=1.7.1
  - py=1.9.0
  - pyodbc=4.0.30
  - pyomo=5.7.1
  - pyopenssl=20.0.1
  - python=3.8.3
  - regex=2020.6.8
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - setuptools=49.6.0
  - wheel=0.36.2
  - pip:
    - ansi2html==1.6.0
    - dash==1.19.0
    - dash-core-components==1.15.0
    - dash-daq==0.5.0
    - dash-html-components==1.1.2
    - dash-renderer==1.9.0
    - dash-table==4.11.2
    - flask-compress==1.8.0
    - flask-cors==3.0.9
    - idaes-pse==1.7.0
    - js2py==0.70
    - jsonpickle==1.5.1
    - jupyter-dash==0.4.0
    - numpy==1.19.4
    - pandas==1.1.1
    - pipwin==0.5.0
    - plotly==4.14.3
    - shapely==1.7.1
    - text-unidecode==1.3